### ISSUE TITLE
Conversion to JSON-LD

### ISSUE THREAD

**Issue by dbouquin** [sigmf/SigMF#108] opened 2019-05-17 23:38 UTC
At the GNU Radio/SETI/Breakthrough hackathon we worked out major updates to the SigMF specification that include converting .sigmf-meta to [JSON-LD](https://json-ld.org/) among other changes and file additions. I'm linking to the reference model we came up with [here](https://www.lucidchart.com/invitations/accept/7ec0c9ba-ca45-40bb-9102-22f3b244ae80). 

I propose making bug fixes to the existing specification and issuing a minor release, followed by a v1 release that would include all changes discussed at the hackathon:

![bouquin_SigMF_recording](https://raw.githubusercontent.com/dbouquin/SigMF/master/images/SigMF_recording.png)

![bouquin_SigMF_spec](https://raw.githubusercontent.com/dbouquin/SigMF/master/images/SigMF_overview.png)

**Comment by bhilburn** [comment] 2019-07-10 20:04
Tagging this for v0.1.0 development.

**Comment by n-west** [comment] 2020-02-26 17:47
I'm not sure I follow what the significance of linked data is, can you help me understand it? How would an existing .sigmf-meta file change to become linked data?

**Comment by gershwinlabs** [comment] 2020-09-14 19:53
JSON-LD is neat, but it doesn't seem mainstream enough yet to satisfy design requirement 3 (minimal requirements and dependencies).  This can also be a problematic at runtime since disconnected devices wouldn't have access to the externally-linked contexts (essentially a runtime dependency).

**Comment by bhilburn** [comment] 2021-05-26 14:52
Marking this for v2.x

**Comment by Sciumo** [comment] 2024-04-09 15:10
How about now that Google is in the game?
https://mlcommons.github.io/croissant/docs/croissant-spec.html

**Comment by Teque5** [comment] 2024-04-13 17:28
It's still not clear to us how this would improve the spec. It seems to give a resource `@context` with the originating location (?) and perhaps a linked id similar to a `doi`, but it's not clear. I'd like to see some arguments in favor as well as a barebones example.

**Comment by Sciumo** [comment] 2024-04-13 22:16
It's not about the specification, per se, anyone can make a JSON-LD equivalent as I have done.
It's about about data correlation and annotation.
For IEEE 1900.8 we are looking at croissant as a means of generating annotations on existing files.
SigMF is one of many equivalent annotations on ground truth data that already exist.
The problem is one of aggregating the equivalent annotations by convention, and not by contract.

**Comment by 777arc** [comment] 2024-04-13 23:01
If it's not about the SigMF specification then we should close out this issue and bring it up in a different venue.

**Comment by Sciumo** [comment] 2024-04-14 00:53
My point was that is a more general issue that subsumes SigMF.
Regardless. I'll back propagate from our work any elements that are in the SigMF problem domain to my SigMF fork which will have the schema and associated documentation.

**Comment by 777arc** [comment] 2024-04-14 01:41
Good plan, opening a PR off your fork will make it more clear what the actual changes would be, closing.

**Closed by 777arc** 2024-04-14 01:41 UTC
Labels: enhancement
